apiVersion: v1
kind: Service
metadata:
  name: lorawan-simulator-service
  labels:
    app: lorawan-simulator
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-name: "lorawan-simulator-{{ .Values.global.environment }}"
spec:
  selector:
    app: lorawan-simulator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer