apiVersion: v1
kind: Service
metadata:
  name: lorawan-simulator-service
  labels:
    app: lorawan-simulator
spec:
  selector:
    app: lorawan-simulator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer