apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-name: "external-vault-connect"
  name: external-vault-connect
  namespace: default
spec:
  clusterIP: None
  ports:
    - port: 8200
      targetPort: 8200