apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: dev-digitalocean-cluster-store
spec:
  provider:
    vault:
      server: {{ .Values.externalSecret.secretStoreRef.vault.server }}
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: eso
          serviceAccountRef:
            name: eso-sa
            namespace: external-secrets
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
  namespace: {{ .Values.externalSecret.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ .Values.externalSecret.name }}
  data:
    - secretKey: {{ .Values.externalSecret.data.secretKey }}
      remoteRef:
        key: {{ .Values.externalSecret.data.remoteRef.key }}
        property: {{ .Values.externalSecret.data.remoteRef.property }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-sa
  namespace: external-secrets