apiVersion: v2
name: network
description: Networking resources for rriv application
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: ingress-nginx
    repository: https://kubernetes.github.io/ingress-nginx
    version: 4.12.2
    condition: controller.publishService.enabled
  - name: cert-manager
    repository: https://charts.jetstack.io
    version: 1.17.2
