nats:
  enabled: true

config:
  jetstream:
    enabled: true

    memoryStore:
      enabled: true
      maxSize: 256Mi

    fileStore:
      enabled: true
      pvc:
        enabled: true
        size: 256Mi