apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: digitalocean-api-key
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: digitalocean-api-key
  data:
    - secretKey: api-token
      remoteRef:
        key: dev-digitalocean-api-key
        property: api-token