apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rriv
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - rriv.org
        - '*.rriv.org'
        - '*.chirp.rriv.org'
      secretName: rriv-org-tls
  rules:
    - host: rriv.org
      http:
        paths:
          - path: /.well-known/webfinger
            pathType: ImplementationSpecific
            backend:
              service:
                name: webfinger-app
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wix-redirect
                port:
                  number: 80
    - host: auth.rriv.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 80
    - host: vault-dev.rriv.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: external-vault
                port:
                  number: 8200
    - host: chirp.rriv.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chirpstack
                port:
                  number: 8080
    - host: console.chirp.rriv.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chirpstack
                port:
                  number: 8080
---

