apiVersion: v1
kind: Service
metadata:
  name: wix-redirect
  namespace: default
spec:
  selector:
    app: wix-redirect
  ports:
    - port: 80
      targetPort: 80
  clusterIP: None
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wix-redirect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wix-redirect
  template:
    metadata:
      labels:
        app: wix-redirect
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: config-volume
          configMap:
            name: wix-redirect-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wix-redirect-config
  namespace: default
data:
  default.conf: |
    server {
      listen 80;
      return 301 https://www.rriv.org$request_uri;
    }
