apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.externalSecret.secretStoreRef.name }}
  namespace: {{ .Values.externalSecret.secretStoreRef.namespace }}
spec:
  provider:
    vault:
      server: {{ .Values.externalSecret.secretStoreRef.vault.server }}
      path: {{ .Values.externalSecret.secretStoreRef.vault.path }}
      version: {{ .Values.externalSecret.secretStoreRef.vault.version }}
      auth:
        kubernetes:
          mountPath: kubernetes-rriv
          role: services-external-secrets
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets

