apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rriv
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: {{ .Values.certificate.issuerRef.name }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
{{ toYaml .Values.certificate.dnsNames | indent 6 }}
      secretName: {{ .Values.ingress.secretName }}
  rules:
    - host: {{ .Values.ingress.hosts.keycloak }}
      http:
        paths:
          - path: /.well-known/webfinger
            pathType: ImplementationSpecific
            backend:
              service:
                name: webfinger-app
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 80
    - host: {{ .Values.ingress.hosts.vault }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: external-vault-connect
                port:
                  number: 8200
    - host: {{ .Values.ingress.hosts.chirpstack }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chirpstack
                port:
                  number: 8080
    - host: {{ .Values.ingress.hosts.chirpstackConsole }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chirpstack
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rriv-data-api
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: {{ .Values.certificate.issuerRef.name }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.ingress.hosts.dataApi }}
      secretName: {{ .Values.ingress.secretName }}
  rules:
    - host: {{ .Values.ingress.hosts.dataApi }}
      http:
        paths:
          - path: /data(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: data-api
                port:
                  number: 80
          - path: /rriv(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: rriv-api
                port:
                  number: 80


