apiVersion: v1
kind: ServiceAccount
metadata:
  name: internal-app
  namespace: default
  annotations:
    kubernetes.io/service-account.name: internal-app
    kubernetes.io/service-account-token-audience: vault