# Note: Consider moving this to a ClusterSecretStore if you want to use it across multiple namespaces.
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecret.secretStoreRef.name }}
  namespace: {{ .Values.externalSecret.secretStoreRef.namespace }}
spec:
  provider:
    vault:
      server: {{ .Values.externalSecret.secretStoreRef.vault.server }}
      path: {{ .Values.externalSecret.secretStoreRef.vault.path }}
      version: {{ .Values.externalSecret.secretStoreRef.vault.version }}
      auth:
        kubernetes:
          mountPath: kubernetes-rriv
          role: cert-manager-external-secrets
          serviceAccountRef:
            name: eso-sa
            namespace: {{ .Values.externalSecret.secretStoreRef.namespace }}

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
  namespace: {{ .Values.externalSecret.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ .Values.externalSecret.name }}
  data:
    - secretKey: {{ .Values.externalSecret.data.secretKey }}
      remoteRef:
        key: {{ .Values.externalSecret.data.remoteRef.key }}
        property: {{ .Values.externalSecret.data.remoteRef.property }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-sa
  namespace: {{ .Values.externalSecret.secretStoreRef.namespace }}