apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rriv
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
{{ toYaml .Values.certificate.dnsNames | indent 6 }}
      secretName: {{ .Values.ingress.secretName }}
  rules:
    - host: rriv.org
      http:
        paths:
          - path: /.well-known/webfinger
            pathType: ImplementationSpecific
            backend:
              service:
                name: webfinger-app
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wix-redirect
                port:
                  number: 80
    - host: {{ .Values.ingress.hosts.keycloak }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 80
    - host: {{ .Values.ingress.hosts.vault }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: external-vault
                port:
                  number: 8200
    - host: {{ .Values.ingress.hosts.chirpstack }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chirpstack
                port:
                  number: 8080
    - host: {{ .Values.ingress.hosts.chirpstackConsole }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chirpstack
                port:
                  number: 8080
---

