server:
  ha:
    enabled: true
    raft:
      enabled: true
      config: |
        seal "awskms" {
          region = "us-west-1"
          secret_key = ""
          access_key = ""
          kms_key_id = ""
        }
        listener "tcp" {
          address = "127.0.0.1:8200"
          cluster_address = "127.0.0.1:8201"
          tls_cert_file = "/vault/userconfig/vault-tls/vault.crt"
          tls_key_file = "/vault/userconfig/vault-tls/vault.key"
        }
        storage "raft" {
          path = "/vault/data"
          node_id = "node1"
        }
        cluster_addr = "http://127.0.0.1:8201"
        api_addr = "https://127.0.0.1:8200"
        disable_mlock = true
        ui = true
    replicas: 1
    dataStorage:
      enabled: true
      size: 1Gi
      storageClass: standard
