apiVersion: v1
data:
  001-init-chirpstack.sh:
    #!/bin/bash
    set -e
    echo "starting psql"
    echo $POSTGRES_USER

    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname="chirpstack" <<-EOSQL
        create extension pg_trgm;
        create extension hstore;
    EOSQL
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: postgres
  name: postgres-cm0
