apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    io.kompose.service: redis
spec:
  selector:
    io.kompose.service: redis
  ports:
    - protocol: TCP
      port: 6379           # The port on which the service will be exposed
      targetPort: 6379      
  type: ClusterIP           # Exposes the service only within the cluster (default behavior)