apiVersion: v1
kind: Service
metadata:
  name: external-vault
  namespace: default  # Use the same namespace where your Vault Pod is running
spec:
  selector:
    app: vault  # This label should match the label on your Vault Pod
  ports:
    - protocol: TCP
      port: 8200         # Port clients will connect to
      targetPort: 8200   # Port on the Vault container
