apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'keycloak-role'
        vault.hashicorp.com/audience: "vault"
        vault.hashicorp.com/agent-inject-secret-credentials.txt: 'secret/data/dev-keycloak-creds'
        # escape vault template syntax for Helm
        vault.hashicorp.com/agent-inject-template-credentials: |
          {{`{{- with secret "secret/data/dev-keycloak-creds" -}}`}}
          export KC_BOOTSTRAP_ADMIN_USERNAME={{`{{ .Data.data.username }}`}}
          export KC_BOOTSTRAP_ADMIN_PASSWORD={{`{{ .Data.data.password }}`}}
          export DB_USER="{{`{{ .Data.data.username }}`}}"
          export DB_PASSWORD="{{`{{ .Data.data.password }}`}}"
          export DB_DATABASE="{{`{{ .Data.data.database }}`}}"
          export DB_ADDR="{{`{{ .Data.data.host }}`}}"
          {{`{{- end }}`}}
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.0.7
          args: {{ .Values.keycloak.extraArgs | toJson }}
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          env:
            - name: KC_PROXY_HEADERS
              value: "xforwarded"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: DB_VENDOR
              value: postgres
            - name: DB_USER
              value: "$(DB_USER)"
            - name: DB_PASSWORD
              value: "$(DB_PASSWORD)"
            - name: DB_ADDR
              value: "$(DB_ADDR)"
            - name: DB_DATABASE
              value: "$(DB_DATABASE)"
            - name: KEYCLOAK_ADMIN
              value: "$(KC_BOOTSTRAP_ADMIN_USERNAME)"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "$(KC_BOOTSTRAP_ADMIN_PASSWORD)"
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
