apiVersion: v1
kind: ServiceAccount
metadata:
  name: rriv-keycloak
  namespace: default
  annotations:
    kubernetes.io/service-account.name: rriv-keycloak
    kubernetes.io/service-account-token-audience: vault