apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: keycloak-static-secret
  namespace: default
spec:
  type: kv-v2

  # mount path
  mount: secret/data

  # path of the secret
  path: dev-vault-db-creds

  # dest k8s secret
  destination:
    name: keycloak-db-creds
    create: true

  # static secret refresh interval
  refreshAfter: 30s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: static-auth