apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: chirpstack-rest-api
  name: chirpstack-rest-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: chirpstack-rest-api
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'webapp'
        vault.hashicorp.com/auth-path: 'auth/kubernetes-rriv'
        vault.hashicorp.com/agent-inject-secret-credentials.txt: 'secret/data/{{ .Values.environment }}-chirpstack-db-creds'
        vault.hashicorp.com/agent-inject-template-credentials: |
          {{`{{- with secret "secret/data/`}}{{ .Values.environment }}{{`-chirpstack-db-creds" -}}`}}
          export POSTGRES_CONN_STRING={{`{{ .Data.data.pg_chirpstack_connection_string }}`}}
          {{`{{- end }}`}}
      
      labels:
        io.kompose.service: chirpstack-rest-api
    spec:
      serviceAccountName: internal-app
      containers:
        - args:
            - --server
            - chirpstack:8080
            - --bind
            - 0.0.0.0:8090
            - --insecure
          image: chirpstack/chirpstack-rest-api:4
          name: chirpstack-rest-api
          command:
            - /bin/sh
            - -c
            - |
              while [ ! -f /vault/secrets/credentials ]; do
                echo "Waiting for secrets file...";
                sleep 2;
              done;
              echo "Secrets file found!";
              source /vault/secrets/credentials;
              /usr/bin/chirpstack-rest-api
          ports:
            - containerPort: 8090
              protocol: TCP
      restartPolicy: Always
