# Load balancer that exposes chirpstack app, chrirpstack gateway bridge, and MQTT
apiVersion: v1
kind: Service
metadata:
  labels:
    app: chirpstack
  name: chirpstack
spec:
  ports:
    - name: "chirpstack"
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: "http"
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: chirpstack
  type: LoadBalancer