apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-name: "chirpstack-rest-api"
  labels:
    app: chirpstack-rest-api
  name: chirpstack-rest-api
spec:
  ports:
    - name: "8090"
      port: 8090
      targetPort: 8090
  selector:
    app: chirpstack-rest-api
