apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-bridge-proxy
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway-bridge-proxy
  template:
    metadata:
      labels:
        app: gateway-bridge-proxy
    spec:
      containers:
      - name: nginx
        image: nginx:1.25-alpine
        ports:
{{- range $index, $channelPlan := .Values.channelPlans }}
        - containerPort: {{ add 1701 $index }}
          protocol: UDP
{{- end }}
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: nginx-config
        configMap:
          name: gateway-bridge-proxy-config
