apiVersion: v1
kind: Service
metadata:
  labels:
    app: mosquitto
  name: mosquitto
spec:
  ports:
    - name: "1883"
      port: 1883
      targetPort: 1883
  selector:
    app: mosquitto
  type: ClusterIP
