apiVersion: v1
data:
  001-init-chirpstack.sh: |
    #!/bin/bash
    set -e
    echo "starting psql"
    echo $POSTGRES_USER

    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname="chirpstack" <<-EOSQL
        create extension pg_trgm;
        create extension hstore;
    EOSQL
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: postgres
  name: postgres-cm0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-cm1
  labels:
    io.kompose.service: postgres
data:
  000-init-user.sh: |
    #!/bin/bash
    set -e
    echo "Creating chirpstack user and database..."
    
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname="postgres" <<-EOSQL
        CREATE ROLE chirpstack WITH LOGIN PASSWORD 'chirpstack';
        CREATE DATABASE chirpstack WITH OWNER chirpstack;
        GRANT ALL PRIVILEGES ON DATABASE chirpstack TO chirpstack;
    EOSQL
    
    echo "Granting schema permissions..."
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname="chirpstack" <<-EOSQL
        GRANT CREATE, USAGE ON SCHEMA public TO chirpstack;
        GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO chirpstack;
        GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO chirpstack;
        ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO chirpstack;
        ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO chirpstack;
    EOSQL
    
    echo "chirpstack user and database created successfully with proper permissions"