apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-name: "redis"
  name: redis
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379           # The port on which the service will be exposed
      targetPort: 6379      
  type: ClusterIP           # Exposes the service only within the cluster (default behavior)