---
# Source: network/templates/cluster-secret-store.yaml
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: cluster-secret-store
  namespace: external-secrets
spec:
  provider:
    vault:
      server: https://vault-dev.rriv.org:8200
      path: secret
      version: v1
      auth:
        kubernetes:
          mountPath: kubernetes-rriv
          role: services-external-secrets
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
