---
apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: default
spec:
  ports:
  - name: vault
    protocol: TCP
    port: 8200
    targetPort: 8200
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8200
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8200
---
# Does this belong in the main rriv-dev cluster?
apiVersion: v1
kind: Endpoints
metadata:
  name: vault
subsets:
  - addresses:
      - ip: {{ .Values.externalVaultIP }}
    ports:
      - port: 8200
