apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secretsmanager
  namespace: vault
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: vault-aws-access-key
            key: AWS_ACCESS_KEY_ID
            namespace: vault
          secretAccessKeySecretRef:
            name: vault-aws-access-key
            key: AWS_SECRET_ACCESS_KEY
            namespace: vault
          