apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "{{ .Values.global.environment }}-digitalocean-dns-api-key"
  namespace: vault
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: "{{ .Values.global.environment }}-digitalocean-dns-api-key"
  data:
    - secretKey: api-token
      remoteRef:
        key: "rriv-{{ .Values.global.environment }}-do-dns-api-key"
        property: api_token
