---
apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: default
spec:
  ports:
  - name: vault
    protocol: TCP
    port: 8200
    targetPort: 8200
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8200
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8200
